/**
 * Restcountries
 * API for restcountries.eu
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Currencies model module.
 * @module model/Currencies
 * @version 1.0.0
 */
class Currencies {
    /**
     * Constructs a new <code>Currencies</code>.
     * Model for Currencies
     * @alias module:model/Currencies
     * @param code {String} 
     */
    constructor(code) { 
        
        Currencies.initialize(this, code);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code) { 
        obj['code'] = code;
    }

    /**
     * Constructs a <code>Currencies</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Currencies} obj Optional instance to populate.
     * @return {module:model/Currencies} The populated <code>Currencies</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Currencies();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} code
 */
Currencies.prototype['code'] = undefined;

/**
 * @member {String} name
 */
Currencies.prototype['name'] = undefined;

/**
 * @member {String} symbol
 */
Currencies.prototype['symbol'] = undefined;






export default Currencies;

