/**
 * Restcountries
 * API for restcountries.eu
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Languages model module.
 * @module model/Languages
 * @version 1.0.0
 */
class Languages {
    /**
     * Constructs a new <code>Languages</code>.
     * Model for Languages
     * @alias module:model/Languages
     * @param iso6391 {String} 
     */
    constructor(iso6391) { 
        
        Languages.initialize(this, iso6391);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, iso6391) { 
        obj['iso639_1'] = iso6391;
    }

    /**
     * Constructs a <code>Languages</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Languages} obj Optional instance to populate.
     * @return {module:model/Languages} The populated <code>Languages</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Languages();

            if (data.hasOwnProperty('iso639_1')) {
                obj['iso639_1'] = ApiClient.convertToType(data['iso639_1'], 'String');
            }
            if (data.hasOwnProperty('iso639_2')) {
                obj['iso639_2'] = ApiClient.convertToType(data['iso639_2'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('nativeName')) {
                obj['nativeName'] = ApiClient.convertToType(data['nativeName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} iso639_1
 */
Languages.prototype['iso639_1'] = undefined;

/**
 * @member {String} iso639_2
 */
Languages.prototype['iso639_2'] = undefined;

/**
 * @member {String} name
 */
Languages.prototype['name'] = undefined;

/**
 * @member {String} nativeName
 */
Languages.prototype['nativeName'] = undefined;






export default Languages;

