/**
 * Restcountries
 * API for restcountries.eu
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RegionalBlocs model module.
 * @module model/RegionalBlocs
 * @version 1.0.0
 */
class RegionalBlocs {
    /**
     * Constructs a new <code>RegionalBlocs</code>.
     * Model for RegionalBlocs
     * @alias module:model/RegionalBlocs
     * @param acronym {String} 
     */
    constructor(acronym) { 
        
        RegionalBlocs.initialize(this, acronym);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, acronym) { 
        obj['acronym'] = acronym;
    }

    /**
     * Constructs a <code>RegionalBlocs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegionalBlocs} obj Optional instance to populate.
     * @return {module:model/RegionalBlocs} The populated <code>RegionalBlocs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegionalBlocs();

            if (data.hasOwnProperty('acronym')) {
                obj['acronym'] = ApiClient.convertToType(data['acronym'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('otherAcronyms')) {
                obj['otherAcronyms'] = ApiClient.convertToType(data['otherAcronyms'], ['String']);
            }
            if (data.hasOwnProperty('otherNames')) {
                obj['otherNames'] = ApiClient.convertToType(data['otherNames'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} acronym
 */
RegionalBlocs.prototype['acronym'] = undefined;

/**
 * @member {String} name
 */
RegionalBlocs.prototype['name'] = undefined;

/**
 * @member {Array.<String>} otherAcronyms
 */
RegionalBlocs.prototype['otherAcronyms'] = undefined;

/**
 * @member {Array.<String>} otherNames
 */
RegionalBlocs.prototype['otherNames'] = undefined;






export default RegionalBlocs;

