/**
 * Restcountries
 * API for restcountries.eu
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Translations model module.
 * @module model/Translations
 * @version 1.0.0
 */
class Translations {
    /**
     * Constructs a new <code>Translations</code>.
     * Model for Translations
     * @alias module:model/Translations
     * @param br {String} 
     */
    constructor(br) { 
        
        Translations.initialize(this, br);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, br) { 
        obj['br'] = br;
    }

    /**
     * Constructs a <code>Translations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Translations} obj Optional instance to populate.
     * @return {module:model/Translations} The populated <code>Translations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Translations();

            if (data.hasOwnProperty('br')) {
                obj['br'] = ApiClient.convertToType(data['br'], 'String');
            }
            if (data.hasOwnProperty('de')) {
                obj['de'] = ApiClient.convertToType(data['de'], 'String');
            }
            if (data.hasOwnProperty('es')) {
                obj['es'] = ApiClient.convertToType(data['es'], 'String');
            }
            if (data.hasOwnProperty('fa')) {
                obj['fa'] = ApiClient.convertToType(data['fa'], 'String');
            }
            if (data.hasOwnProperty('fr')) {
                obj['fr'] = ApiClient.convertToType(data['fr'], 'String');
            }
            if (data.hasOwnProperty('hr')) {
                obj['hr'] = ApiClient.convertToType(data['hr'], 'String');
            }
            if (data.hasOwnProperty('it')) {
                obj['it'] = ApiClient.convertToType(data['it'], 'String');
            }
            if (data.hasOwnProperty('ja')) {
                obj['ja'] = ApiClient.convertToType(data['ja'], 'String');
            }
            if (data.hasOwnProperty('nl')) {
                obj['nl'] = ApiClient.convertToType(data['nl'], 'String');
            }
            if (data.hasOwnProperty('pt')) {
                obj['pt'] = ApiClient.convertToType(data['pt'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} br
 */
Translations.prototype['br'] = undefined;

/**
 * @member {String} de
 */
Translations.prototype['de'] = undefined;

/**
 * @member {String} es
 */
Translations.prototype['es'] = undefined;

/**
 * @member {String} fa
 */
Translations.prototype['fa'] = undefined;

/**
 * @member {String} fr
 */
Translations.prototype['fr'] = undefined;

/**
 * @member {String} hr
 */
Translations.prototype['hr'] = undefined;

/**
 * @member {String} it
 */
Translations.prototype['it'] = undefined;

/**
 * @member {String} ja
 */
Translations.prototype['ja'] = undefined;

/**
 * @member {String} nl
 */
Translations.prototype['nl'] = undefined;

/**
 * @member {String} pt
 */
Translations.prototype['pt'] = undefined;






export default Translations;

