export { Question1 } from './question1/Question1'
export { question1Reducer } from './question1/question1Slice'
export { Question2 } from './question2/Question2'
export { question2Reducer } from './question2/question2Slice'
export { Question3 } from './question3/Question3'
export { question3Reducer } from './question3/question3Slice'
export { Question4 } from './question4/Question4'
export { Question5 } from './question5/Question5'
